[workspace]
resolver = "2"
members = [
    "crates/embala",
    "crates/embala-msi",
    "crates/embala-nupkg",
    "crates/embala-pkg",
    "crates/embala-setup",
    "crates/embala-setup-runtime",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
authors = ["Carlos Hernandez <carlos@hrndz.ca>"]
repository = "https://github.com/hurricanehrndz/embala"
license = "MIT"
publish = true
